#!/bin/bash

session=$3
tmux has-session -t $session 2>/dev/null
if [ $? != 0 ]; then
    tmux new-session -d -s $session \; split-window -h \; split-window -p 60 
    tmux send-keys -t $session:0.0 "clear && ./client $1 $2" C-m
    tmux send-keys -t $session:0.1 "clear && figlet MultiCLI | lolcat && read n" C-m
    tmux send-keys -t $session:0.2 "./get-input $3" C-m 
fi

tmux attach -t $session



